name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Print DIR1
      run: ls ./usbSerialForAndroid
    - name: Print DIR2
      run: ls ./usbSerialForAndroid/build
    - name: Print DIR3
      run: ls ./usbSerialForAndroid/build/aar/
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: ./build/outputs/aar/debug.aar
    - name: Upload aar
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: ./build/outputs/aar/*.aar
    - name: Upload aar2
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: ./build/outputs/aar/usb-serial-for-android3.5.2beta.aar
