name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Print DIR4
      run: ls ./usbSerialForAndroid/build/outputs/aar/
    - name: Upload aar
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: ./usbSerialForAndroid/build/outputs/aar/*.aar
